print("Randomizer patch for LawnStrings_en")
file_object = open('Content/LawnStrings_en.txt', 'a')
print("Patching")
file_object.write("\n\n[CRAZY_DAVE_2035]\n")
file_object.write("{NO_SOUND}{NO_CLICK}Buy this plant to use it in your level!\n")
file_object.write("\n\n[CRAZY_DAVE_4100]\n")
file_object.write("Greetings, neighbor!\n")
file_object.write("\n\n[CRAZY_DAVE_4101]\n")
file_object.write("The name's Crazy Dave.\n")
file_object.write("\n\n[CRAZY_DAVE_4102]\n")
file_object.write("But you can just call me Crazy Dave.\n")
file_object.write("\n\n[CRAZY_DAVE_4103]\n")
file_object.write("It seems like Mr. Boss guy has managed to use my time machine\n")
file_object.write("Now he randomized all the days in the year 2009!\n")
file_object.write("\n\n[CRAZY_DAVE_4104]\n")
file_object.write("{SHAKE}So be warned!{MOUTH_BIG_SMILE}\n")
file_object.write("\n\n[CRAZY_DAVE_4105]\n")
file_object.write("See you later in the evening!\n")
file_object.write("I've got a surprise for you later on.\n")
file_object.write("\n\n[FOUND_SUBURBAN_ALMANAC_NEW]\n")
file_object.write("You found another suburban almanac!\n")
file_object.write("\n\n[SUBURBAN_ALMANAC_DESCRIPTION_NEW]\n")
file_object.write("There is no need for another one of these\n")
file_object.write("\n\n[WATERING_CAN_DESCRIPTION_NEW]\n")
file_object.write("DO NOT CONTINUE ADVENTURE MODE YET!\n")
file_object.write("GO BACK TO THE MAIN MENU AND GO TO\n")
file_object.write("THE ZEN GARDEN AND FINISH THE TUTORIAL!\n")
print("Patching done")
# Close the file
file_object.close()



