print("PlantsVsZombies.net Randomizer")
print("Make sure you get the files from the Windows Phone version of Plants vs. Zombies and put it's Content folder into the same folder as the installer and don't replace any of the files that are already in the Content folder")
print("Put also the lawnstrings files into the content folder")
print("Please note that there may be bugs and issues with this randomizer.")
print("")
SeedNum = input("Type in your seed name >")
print("")
exec(open("plants.py").read())
print("")
exec(open("Upgradeplants.py").read())
print("")
exec(open("ZombieWaveAmount.py").read())
print("")
exec(open("LawnstringENPatcher.py").read())
print("")
print("Now you can start setting up the game.")
print("Open up the sln file with Visual Studio 2019 first")
print("Build the PC port projects (Lawn_PCDX and Lawn_PCGL) (Android port is untested)")
print("put the Content folder into the same folder as the compiled .exe of the PC port project (Lawn_PCDX or Lawn_PCGL).")
print("and now you're ready to play the randomizer!")
input("press enter to leave >")
